### ISSUE TITLE
shopping-list example TypeError: (0 , _resolveScripts.stop) is not a function

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve#1097]
1) npx create-resolve-app resolve-example -e shopping-list
2) cd resolve-example/
3) yarn dev

yarn run v1.12.3
$ babel-node ./run.js dev
(node:63549) UnhandledPromiseRejectionWarning: TypeError: (0 , _resolveScripts.stop) is not a function
    at _callee$ (/Users/ykrutilin/Desktop/resolve-example/run.js:80:11)
    at tryCatch (/Users/ykrutilin/Desktop/resolve-example/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/ykrutilin/Desktop/resolve-example/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/ykrutilin/Desktop/resolve-example/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/ykrutilin/Desktop/resolve-example/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/ykrutilin/Desktop/resolve-example/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /Users/ykrutilin/Desktop/resolve-example/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at /Users/ykrutilin/Desktop/resolve-example/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
    at Object.<anonymous> (/Users/ykrutilin/Desktop/resolve-example/run.js:20:6)
(node:63549) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:63549) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by MrCheater** [comment]
Can't reproduce the issue. 
https://github.com/reimagined/resolve/blob/master/packages/core/resolve-scripts/src/index.js#L28

**Comment by MrCheater** [comment]
![](file:///home/mrcheater/shplist.png)

**Comment by MrCheater** [comment]
![shplist](https://user-images.githubusercontent.com/5055654/58161632-46b2d680-7c89-11e9-9991-4ff13d31cf6f.png)

**Comment by krutilin** [comment]
Global cache in the yarn. Maybe we should add a note about global caching in the documentation.
