### ISSUE TITLE
Event broker does not stop after server stop. And takes the port.

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve#1112]
Event broker does not stop sometimes and still takes the port. But we don't know which post is occupied from this error message.
```
yarn dev
yarn run v1.12.3
$ cd app && node ./run.js dev
[ Client ] Time: 7642ms
Built at: 05/24/2019 1:22:37 PM
[ Server local entry point ] Time: 6113ms
Built at: 05/24/2019 1:22:35 PM
[ Local event broker entry point ] Time: 857ms
Built at: 05/24/2019 1:22:30 PM
Event broker has run into an error: Error: Address already in use
    at exports.Socket.Socket.bindSync (/Users/ykrutilin/Desktop/brewcomputer/app/node_modules/zeromq/lib/index.js:460:13)
    at Object.initSockets (/Users/ykrutilin/Desktop/brewcomputer/app/node_modules/resolve-local-event-broker/lib/init-sockets.js:15:14)
    at createAndInitBroker (/Users/ykrutilin/Desktop/brewcomputer/app/node_modules/resolve-local-event-broker/lib/create-and-init-broker.js:32:14)

You can now view brewcomputer-app in the browser.

  Local:            http://localhost:3000/
  On Your Network:  http://172.22.4.129:3000/

Note that the development build is not optimized.
To create a production build, use:
  yarn build.
  yarn start.
```

**Comment by IhostVlad** [comment]
Closing due inactivity within long time period. Please reopen issue if problem is still actual.
