### ISSUE TITLE
Make error messages clearer

### ISSUE THREAD

**Issue by brainstream** [reimagined/resolve#1125]
I'm using **reSolve 0.13.2**

Sometime while develop an application I got error messages with a call stack which doesn't help me to identify the cause of error.

For example. When my command doesn't return an event

```js
testCommand: (state, payload) => {}
```

I have following call stack 

```
TypeError: Cannot read property 'type' of undefined
    at _callee4$ (C:\Projects\nps\npssvc\node_modules\resolve-command\dist\index.js:226:23)
    at tryCatch (C:\Projects\nps\npssvc\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (C:\Projects\nps\npssvc\node_modules\regenerator-runtime\runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Projects\nps\npssvc\node_modules\regenerator-runtime\runtime.js:114:21)
    at asyncGeneratorStep (C:\Projects\nps\npssvc\node_modules\@babel\runtime\helpers\asyncToGenerator.js:5:24)
    at _next (C:\Projects\nps\npssvc\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:9)
    at <anonymous>
```

Actually, any error in the reSolve infrastructure doesn't show a real mistake.

**Comment by MrCheater** [comment]
https://github.com/reimagined/resolve/blob/master/packages/core/resolve-command/test/index.test.js#L518-L639

https://github.com/reimagined/resolve/blob/master/packages/core/resolve-command/test/index.test.js#L680-L711

In version 0.20.23 the problem is already fixed
