### ISSUE TITLE
Event broker has run into an error: TypeError: Cannot read property 'socket' of undefined throws on resole application start

### ISSUE THREAD

**Issue by sanoki** [reimagined/resolve#1241]
We can no more launch resolve applications (and your examples). It looks that some dependencies use a new zeromq 6 package that is not supported now.

**To Reproduce**
1. open hello-world examle
2. npm install. 
3. npm run. The application fails:
[ Client ] Time: 13761ms
Built at: 11/12/2019 10:37:17 AM
[ Server local entry point ] Time: 4068ms
Built at: 11/12/2019 10:37:08 AM
[ Local event broker entry point ] Time: 425ms
Built at: 11/12/2019 10:37:04 AM
Event broker has run into an error: TypeError: Cannot read property 'socket' of undefined

**Additional Info**
 - OS: 3 different PC with Windows 10
 - Resolve version: 0.20.28

Full log:
**PS C:\Users\yekim.alexander\Downloads\resolve-master\resolve-master\examples\hello-world> npm install**
```
> sqlite3@4.1.0 install C:\Users\yekim.alexander\Downloads\resolve-master\resolve-master\examples\hello-world\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
[sqlite3] Success: "C:\Users\yekim.alexander\Downloads\resolve-master\resolve-master\examples\hello-world\node_modules\sqlite3\lib\binding\node-v72-win32-x64\node_sqlite3.node" is installed via remote

> core-js@2.6.10 postinstall C:\Users\yekim.alexander\Downloads\resolve-master\resolve-master\examples\hello-world\node_modules\core-js
> node postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> resolve-zeromq@0.20.28 postinstall C:\Users\yekim.alexander\Downloads\resolve-master\resolve-master\examples\hello-world\node_modules\resolve-zeromq
> node scripts/install.js


> zeromq@6.0.0-beta.3 install C:\Users\yekim.alexander\Downloads\resolve-master\resolve-master\examples\hello-world\node_modules\resolve-zeromq\optional\node_modules\zeromq
> node-gyp-build

+ zeromq@6.0.0-beta.3
added 3 packages from 46 contributors in 1.4s

> parse-domain@2.3.4 postinstall C:\Users\yekim.alexander\Downloads\resolve-master\resolve-master\examples\hello-world\node_modules\parse-domain
> run-s build:tries


> parse-domain@2.3.4 build:tries C:\Users\yekim.alexander\Downloads\resolve-master\resolve-master\examples\hello-world\node_modules\parse-domain
> node scripts/build-tries.js

Downloading public suffix list from https://publicsuffix.org/list/public_suffix_list.dat... (node:11768) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
ok
Writing C:\Users\yekim.alexander\Downloads\resolve-master\resolve-master\examples\hello-world\node_modules\parse-domain\build\tries\icann.complete.json... ok
Writing C:\Users\yekim.alexander\Downloads\resolve-master\resolve-master\examples\hello-world\node_modules\parse-domain\build\tries\icann.light.json... ok
Writing C:\Users\yekim.alexander\Downloads\resolve-master\resolve-master\examples\hello-world\node_modules\parse-domain\build\tries\private.complete.json... ok
Running sanity check... C:\Users\yekim.alexander\Downloads\resolve-master\resolve-master\examples\hello-world\node_modules\parse-domain\node_modules\.bin\jest:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11

Could not update list of known top-level domains for parse-domain because of "Command failed: C:\Program Files\nodejs\node.exe C:\Users\yekim.alexander\Downloads\resolve-master\resolve-master\examples\hello-world\node_modules\parse-domain\node_modules\.bin\jest
C:\Users\yekim.alexander\Downloads\resolve-master\resolve-master\examples\hello-world\node_modules\parse-domain\node_modules\.bin\jest:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
"
Using possibly outdated prebuilt list from Sat Nov 02 2019
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 2041 packages from 1552 contributors and audited 1794914 packages in 60.972s
found 44 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```
**PS C:\Users\yekim.alexander\Downloads\resolve-master\resolve-master\examples\hello-world> npm run dev**                   
```
> hello-world@0.20.28 dev C:\Users\yekim.alexander\Downloads\resolve-master\resolve-master\examples\hello-world
> babel-node ./run.js dev

[ Client ] Time: 5282ms
Built at: 11/12/2019 11:55:28 AM
[ Server local entry point ] Time: 3280ms
Built at: 11/12/2019 11:55:26 AM

WARNING in ./node_modules/resolve-runtime/lib/common/handlers/markup-handler.js
Module not found: Error: Can't resolve 'styled-components' in 'C:\Users\yekim.alexander\Downloads\resolve-master\resolve-master\examples\hello-world\node_modules\resolve-runtime\lib\common\handlers'
 @ ./node_modules/resolve-runtime/lib/common/handlers/markup-handler.js
 @ ./node_modules/resolve-runtime/lib/common/handlers/main-handler.js
 @ ./node_modules/resolve-runtime/lib/local/init-express.js
 @ ./node_modules/resolve-runtime/lib/local/index.js
 @ ./node_modules/resolve-scripts/lib/alias/$resolve.localEntry.js
 @ multi @babel/polyfill ./node_modules/resolve-scripts/lib/alias/$resolve.localEntry.js
[ Local event broker entry point ] Time: 795ms
Built at: 11/12/2019 11:55:24 AM
Event broker has run into an error: TypeError: Cannot read property 'socket' of undefined
    at Object.initSockets (C:\Users\yekim.alexander\Downloads\resolve-master\resolve-master\examples\hello-world\node_modules\resolve-local-event-broker\lib\init-sockets.js:11:31)
    at createAndInitBroker (C:\Users\yekim.alexander\Downloads\resolve-master\resolve-master\examples\hello-world\node_modules\resolve-local-event-broker\lib\create-and-init-broker.js:34:14)
    at async C:\Users\yekim.alexander\Downloads\resolve-master\resolve-master\examples\hello-world\dist\common\local-entry\local-bus-broker.js:137:24
PS C:\Users\yekim.alexander\Downloads\resolve-master\resolve-master\examples\hello-world>
```

**Comment by MrCheater** [comment]
Try update your application to resolve 0.20.29, remove node_modules and yarn.lock

**Comment by sanoki** [comment]
update to 0.20.29 solved my problem, thanks.
