### ISSUE TITLE
Versioning problem in "create-resolve-app"

### ISSUE THREAD

**Issue by MrCheater** [reimagined/resolve#1286]
**Describe the bug**
An old version of create-resolve-app downloads and installs a new version of an example. After installation, the old version of an example does not work.

```sh
yarn dev 
yarn run v1.21.1
warning ../package.json: No license field
warning ../../../package.json: No license field
$ babel-node ./run.js dev
Error: Resolve Config validation failed: [
  {
    "keyword": "additionalProperties",
    "dataPath": "",
    "schemaPath": "#/additionalProperties",
    "params": {
      "additionalProperty": "clientEntries"
    },
    "message": "should NOT have additional properties"
  }
]
    at validateConfig (/resolve-ts/node_modules/resolve-scripts/src/validate_config.js:120:11)
    at /resolve-ts/node_modules/resolve-scripts/src/generate_custom_mode.js:23:7
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
er
```

**Comment by IhostVlad** [comment]
Fixed in version 0.22.4
