### ISSUE TITLE
elastic-search in hacker-news example does not work with latest 7.5.2 version

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve#1299]
**Describe the bug**
elastic-search in hacker-news example does not work with latest 7.5.2 version

**To Reproduce**
1) Clone hn example. Import some data.
2) Prepare es node in the elastic cloud, the free tier is good enough for it.
3) Recieve on app start
```
  resolve:resolve-runtime:local:init-broker Error while applying events to read-model { listenerId: 'Search',
  lastError:
   { Error: [illegal_argument_exception] Rejecting mapping update to [primary] as the final mapping would have more than 1 type: [user, story]
       at respond (/Users/ykrutilin/Desktop/hacker-news-example/node_modules/elasticsearch/src/lib/transport.js:308:15)
       at checkRespForFailure (/Users/ykrutilin/Desktop/hacker-news-example/node_modules/elasticsearch/src/lib/transport.js:267:7)
       at HttpConnector.<anonymous> (/Users/ykrutilin/Desktop/hacker-news-example/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
       at IncomingMessage.wrapper (/Users/ykrutilin/Desktop/hacker-news-example/node_modules/lodash/lodash.js:4929:19)
       at IncomingMessage.emit (events.js:194:15)
       at endReadableNT (_stream_readable.js:1125:12)
       at process._tickCallback (internal/process/next_tick.js:63:19)
     message:
      '[illegal_argument_exception] Rejecting mapping update to [primary] as the final mapping would have more than 1 type: [user, story]',
     stack:
      'Error: [illegal_argument_exception] Rejecting mapping update to [primary] as the final mapping would have more than 1 type: [user, story]\n    at respond (/Users/ykrutilin/Desktop/hacker-news-example/node_modules/elasticsearch/src/lib/transport.js:308:15)\n    at checkRespForFailure (/Users/ykrutilin/Desktop/hacker-news-example/node_modules/elasticsearch/src/lib/transport.js:267:7)\n    at HttpConnector.<anonymous> (/Users/ykrutilin/Desktop/hacker-news-example/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)\n    at IncomingMessage.wrapper (/Users/ykrutilin/Desktop/hacker-news-example/node_modules/lodash/lodash.js:4929:19)\n    at IncomingMessage.emit (events.js:194:15)\n    at endReadableNT (_stream_readable.js:1125:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)' },
  lastEvent:
   { timestamp: 1580389684052,
     aggregateId: '4798e804-98ee-4f3f-8359-9fa0c204c01e',
     aggregateVersion: 1,
     type: 'UserCreated',
     payload: { name: 'ismdeep' } } } +0ms
```
elastic version
```
{
  "name" : "instance-0000000000",
  "cluster_name" : "19edbe75762b4cc5b488158ba0e1d106",
  "cluster_uuid" : "x2IMGlOJS0iuWyQc5j_Pog",
  "version" : {
    "number" : "7.5.2",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "8bec50e1e0ad29dad5653712cf3bb580cd1afcdf",
    "build_date" : "2020-01-15T12:11:52.313576Z",
    "build_snapshot" : false,
    "lucene_version" : "8.3.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by MrCheater** [comment]
Fixed
