### ISSUE TITLE
Building a read-model failed "ERROR: syntax error at or near "WHERE" 

### ISSUE THREAD

**Issue by MrCheater** [reimagined/resolve#1385]
**Describe the bug**
```
Apr 30 2020 10:39:23: { BadRequestException: ERROR: syntax error at or near "WHERE"
Apr 30 2020 10:39:23: Position: 71
Apr 30 2020 10:39:23: at Object.extractError (/opt/nodejs/node_modules/aws-sdk/lib/protocol/json.js:51:27)
Apr 30 2020 10:39:23: at Request.extractError (/opt/nodejs/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
Apr 30 2020 10:39:23: at Request.callListeners (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
Apr 30 2020 10:39:23: at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
Apr 30 2020 10:39:23: at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/request.js:683:14)
Apr 30 2020 10:39:23: at Request.transition (/opt/nodejs/node_modules/aws-sdk/lib/request.js:22:10)
Apr 30 2020 10:39:23: at AcceptorStateMachine.runTo (/opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:14:12)
Apr 30 2020 10:39:23: at /opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:26:10
Apr 30 2020 10:39:23: at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:38:9)
Apr 30 2020 10:39:23: at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:685:12)
Apr 30 2020 10:39:23: message: 'ERROR: syntax error at or near "WHERE"\n  Position: 71',
```

**To Reproduce**
1. Read-model projection 
```
const changes = {} // empty object
await store.update('Users', { id: aggregateId }, { $set: changes })
```

**Additional context**
 - Read-model-adapter: resolve-readmodel-postgresql-serverless
 - Version 0.23.2

**Comment by MrCheater** [comment]
Fixed in version 0.24.5
