### ISSUE TITLE
Error on server rebuild in "watch" mode

### ISSUE THREAD

**Issue by alexslavr** [reimagined/resolve#1485]
[ Server CommonJS entries ] Time: 5920ms
Built at: 08/05/2020 12:12:38 PM
 
[ Server local entry point, local bus broker, local event store ] Time: 5942ms
Built at: 08/05/2020 12:12:38 PM
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at Socket.socketOnEnd (_http_client.js:426:23)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Socket.socketOnEnd (_http_client.js:426:9)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Error: connect ECONNREFUSED 127.0.0.1:3500
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)

**Comment by max-vasin** [comment]
Cannot reproduce in 0.29.0.
