### ISSUE TITLE
Failed to load events in eventstore adapter if connection is terminated while events loading

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#1901]
Error is thrown on RDS scaling (all connections are terminated while on scaling)

```
TypeError: events.push is not iterable (cannot read property Symbol(Symbol.iterator))
  at loadEventsByCursor (/var/task/node_modules/@resolve-js/eventstore-postgresql-serverless/lib/load-events-by-cursor.js:223:16)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:97:5)
  at connectOnDemandAndCall (/var/task/node_modules/@resolve-js/eventstore-base/lib/wrap-method.js:16:10)
  at loadEvents (/var/task/node_modules/@resolve-js/eventstore-base/lib/load-events.js:11:93)
  at /var/task/node_modules/@resolve-js/eventstore-base/lib/wrap-event-filter.js:24:10
  at connectOnDemandAndCall (/var/task/node_modules/@resolve-js/eventstore-base/lib/wrap-method.js:16:10)
  at async Promise.all (index 0)
  at buildEvents (/var/task/node_modules/@resolve-js/readmodel-postgresql-serverless/lib/build.js:175:18)
  at build (/var/task/node_modules/@resolve-js/readmodel-postgresql-serverless/lib/build.js:462:5)
```

**Comment by MrCheater** [comment]
Fixed in version 0.31.3
