### ISSUE TITLE
Read-model operations error: subscribe _SCHEDULER_

### ISSUE THREAD

**Issue by alexslavr** [reimagined/resolve#2044]
**Describe the bug**
We received the following warnings after the update to version 0.31.10 

```
Read-model operations error: subscribe _SCHEDULER_ error: must be a member of the role whose process is being terminated or member of pg_signal_backend
    at Parser.parseErrorMessage (/var/task/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/var/task/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/var/task/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/var/task/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 156,
  severity: 'ERROR',
  code: '42501',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'misc.c',
  line: '321',
  routine: 'pg_terminate_backend'
}
```

```
Event subscriber "_SCHEDULER_" can't resume subscription due to error "error: must be a member of the role whose process is being terminated or member of pg_signal_backend
    at Parser.parseErrorMessage (/var/task/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/var/task/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/var/task/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/var/task/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)"
```

**Desktop (please complete the following information):**

- ReSolve Version 0.31.10
- Cloud configuration

**Additional context**
Read-model adapter: @resolve-js/readmodel-postgresql

**Comment by MrCheater** [comment]
pg_terminate_backend says:

> pg_terminate_backend(pid int) - Terminate a backend. This is also allowed if the calling role is a member of the role whose backend is being terminated or the calling role has been granted pg_signal_backend, however only superusers can terminate superuser backends.

I think I've found a bug:
https://github.com/reimagined/resolve/blob/d9116d6edee08045854ac3b10a262536852636ac/packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/inline-ledger-force-stop.ts#L30

**Comment by IhostVlad** [comment]
No, it works well for own backend processes, e.g. which was statred with same user (Like `kill` in unix-like OS)
Most likely that meta table reports foreign user PID and obviously it cannot be terminated
Method works well, for example, reset operation heavily depend on it
