### ISSUE TITLE
Some format options does not work in cli, for example domainName

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve#2110]
resolve-cloud list --format={{domainName}}
```
 ERROR  Error: Formatting failed: {{domainName}}                                                                                                    14:19:12
    at renderByTemplate (/Users/ykrutilin/Desktop/brewcomputer/app/node_modules/resolve-cloud/src/utils/std.ts:48:13)
    at /Users/ykrutilin/Desktop/brewcomputer/app/node_modules/resolve-cloud/src/commands/list.ts:15:23
    at Array.map (<anonymous>)
    at /Users/ykrutilin/Desktop/brewcomputer/app/node_modules/resolve-cloud/src/commands/list.ts:14:12
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

error Command failed with exit code 1.
```
resolve v0.33

**Comment by Lykoi18** [comment]
Fixed in version 0.33.1
