### ISSUE TITLE
[resolve-scripts] Add JSON.parse for gqlVariables

### ISSUE THREAD

**Issue by MrCheater** [reimagined/resolve#230]
```
Error: Variables must be provided as an Object where each property is a variable value. Perhaps look to see if an unparsed JSON string was provided.
    at invariant (/home/mrcheater/hacker-news-demo/node_modules/graphql/jsutils/invariant.js:19:11)
    at assertValidExecutionArguments (/home/mrcheater/hacker-news-demo/node_modules/graphql/execution/execute.js:173:153)
    at executeImpl (/home/mrcheater/hacker-news-demo/node_modules/graphql/execution/execute.js:118:3)
    at execute (/home/mrcheater/hacker-news-demo/node_modules/graphql/execution/execute.js:113:150)
    at _callee3$ (/home/mrcheater/hacker-news-demo/node_modules/resolve-query/dist/index.js:188:57)
    at tryCatch (/home/mrcheater/hacker-news-demo/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/mrcheater/hacker-news-demo/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/home/mrcheater/hacker-news-demo/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/mrcheater/hacker-news-demo/node_modules/resolve-query/dist/index.js:15:191)
    at /home/mrcheater/hacker-news-demo/node_modules/resolve-query/dist/index.js:15:361

```

**Comment by IhostVlad** [comment]
Done here https://github.com/reimagined/resolve/pull/232
