### ISSUE TITLE
[create-resolve-app] describe arguments when called without params

### ISSUE THREAD

**Issue by superroma** [reimagined/resolve#346]
Now it gives an error:
```bash
$ create-resolve-app
/usr/local/lib/node_modules/create-resolve-app/bin/index.js:9
let appName = options._unknown[0] || 'resolve-app';
                              ^

TypeError: Cannot read property '0' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/create-resolve-app/bin/index.js:9:31)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```
should be like this (with --help or just options we are having)
```bash
$ create-react-app
Please specify the project directory:
  create-react-app <project-directory>

For example:
  create-react-app my-react-app

Run create-react-app --help to see all options.
```

**Comment by superroma** [comment]
test
