### ISSUE TITLE
Read model adapter error is not informative at all

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#587]
I have no idea what I'm doing wrong and what to do to fix it:
```
Error: Search expression {} is invalid
    at checkCondition (D:\Repositories\okrserver\node_modules\resolve-readmodel-base\dist\check-store-api.js:49:11)
    at _loop2 (D:\Repositories\okrserver\node_modules\resolve-readmodel-base\dist\check-store-api.js:355:5)
    at checkSearchExpression (D:\Repositories\okrserver\node_modules\resolve-readmodel-base\dist\check-store-api.js:367:7)
    at _callee4$ (D:\Repositories\okrserver\node_modules\resolve-readmodel-base\dist\check-store-api.js:595:13)
    at tryCatch (D:\Repositories\okrserver\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\Repositories\okrserver\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (D:\Repositories\okrserver\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (D:\Repositories\okrserver\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at D:\Repositories\okrserver\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
```

**Comment by IhostVlad** [comment]
Done - will be shipped in resolve 0.11.0 version
