### ISSUE TITLE
@babel/runtime/regenerator not found in /my-app/dist/common/aggregates/index.js

### ISSUE THREAD

**Issue by MrCheater** [reimagined/resolve#717]
**Describe the bug**
@babel/runtime/regenerator not found in /my-app/dist/common/aggregates/index.js

**To Reproduce**
1. `cd my-app`
2. `yarn && yarn build`
3. `cd dist/common/aggregates/`
4. `node -e "require('./index.js')"`
5. Error 
```js
Error: Cannot find module '@babel/runtime/regenerator'
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.@babel/runtime/regenerator (/my-app/dist/common/aggregates/index.js:203:18)
at __webpack_require__ (/my-app/dist/common/aggregates/index.js:21:30)
at Object.0 (/my-app/dist/common/aggregates/index.js:179:1)
at __webpack_require__ (/my-app/dist/common/aggregates/index.js:21:30)
at /my-app/dist/common/aggregates/index.js:85:18
at Object.<anonymous> (/my-app/dist/common/aggregates/index.js:88:10)
```
6. `cat package.json`
```js
{
  "name": "my-app-common-aggregates",
  "private": true,
  "version": "0.13.2",
  "main": "./index.js",
  "dependencies": {}
}
```
7. Not found "@babel/runtime/regenerator"

**Expected behavior**
`cat package.json`
```js
{
  "name": "my-app-common-aggregates",
  "private": true,
  "version": "0.13.2",
  "main": "./index.js",
  "dependencies": {
    "@babel/runtime/regenerator": "7.0.0-beta.55" // From /my-app/package.json
  }
}
```

```js
// resolve.config.json
{
   // ...
   polyfills: [
     "@babel/runtime/regenerator"
   ]
   // ...
}
```

**Comment by TatyanaRyzh** [comment]
Fixed in [0.14.0](https://github.com/reimagined/resolve/releases/tag/V0.14.0)
