### ISSUE TITLE
The resolve-todo-example does not work.

### ISSUE THREAD

**Issue by Matosov** [reimagined/resolve#754]
Steps to reproduce:
1. npx create-resolve-app resolve-todo-example -e todo
2. cd resolve-todo-example
3. npm run dev

Result:
> resolve-todo-example@0.14.0 dev /Users/aleksei.matosov/Projects/resolve-todo-example
> babel-node ./index.js dev

/Users/aleksei.matosov/Projects/resolve-todo-example/node_modules/@babel/core/lib/config/validation/options.js:113
    throw new ReferenceError(unknownOptErr);
    ^

ReferenceError: Unknown option: .caller. Check out http://babeljs.io/docs/usage/options/ for more information about options.
    at buildUnknownError (/Users/aleksei.matosov/Projects/resolve-todo-example/node_modules/@babel/core/lib/config/validation/options.js:113:11)
    at Object.keys.forEach.key (/Users/aleksei.matosov/Projects/resolve-todo-example/node_modules/@babel/core/lib/config/validation/options.js:99:57)
    at Array.forEach (<anonymous>)
    at validate (/Users/aleksei.matosov/Projects/resolve-todo-example/node_modules/@babel/core/lib/config/validation/options.js:69:21)
    at loadPrivatePartialConfig (/Users/aleksei.matosov/Projects/resolve-todo-example/node_modules/@babel/core/lib/config/partial.js:38:50)
    at loadFullConfig (/Users/aleksei.matosov/Projects/resolve-todo-example/node_modules/@babel/core/lib/config/full.js:43:39)
    at loadOptions (/Users/aleksei.matosov/Projects/resolve-todo-example/node_modules/@babel/core/lib/config/index.js:27:36)
    at OptionManager.init (/Users/aleksei.matosov/Projects/resolve-todo-example/node_modules/@babel/core/lib/index.js:215:36)
    at compile (/Users/aleksei.matosov/Projects/resolve-todo-example/node_modules/@babel/register/lib/node.js:61:42)
    at compileHook (/Users/aleksei.matosov/Projects/resolve-todo-example/node_modules/@babel/register/lib/node.js:102:12)

**Comment by IhostVlad** [comment]
On `resolve` latest version `0.14.2` everything works properly. 
Example `todo` does not exist anymore - use `nested-list` instead this.
When using `create-resolve-app` with `npx`, check that there is no globally-installed package exist - if so, just uninstall it.

![screenshot from 2018-08-23 11-37-50](https://user-images.githubusercontent.com/14352827/44514513-08bc5e00-a6c9-11e8-891f-01ba19436d9f.png)
