### ISSUE TITLE
[hacker-news] Fix importer

### ISSUE THREAD

**Issue by MrCheater** [reimagined/resolve#878]
**Describe the bug**
Broken `yarn run import`

```sh
/hacker-news/import/importer.js:32
var COMMENT_CREATED = _resolveModuleComments.eventTypes.COMMENT_CREATED;
                                                        ^
TypeError: Cannot read property 'COMMENT_CREATED' of undefined
    at Object.COMMENT_CREATED (/hacker-news/import/importer.js:14:9)
    at Module._compile (module.js:652:30)
    at Module._compile (/hacker-news/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (/hacker-news/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by IhostVlad** [comment]
Fixed on version 0.18.2
