### ISSUE TITLE
resolve-module-auth - Error on open a callback link

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#921]
I use '/auth' route for Azure auth module callback. I go to '/api/auth', then waits for redirect from Microsoft website back to this URL and after that refreshes browser page. It leads to the following error. Reproduced only for URL with params part and not reproduced for URL without params.

```
TypeError: types.json is not a function
    at json (/var/task/node_modules/resolve-api-handler-awslambda/src/index.js:113:76)
    at Object.validateOptionShape [as end] (/var/task/node_modules/resolve-api-handler-awslambda/src/index.js:191:5)
    at end (/var/task/node_modules/resolve-module-auth/src/send_auth_response.js:22:9)
    at /var/task/node_modules/resolve-module-auth/src/api_handler_constructor.js:28:11
    at <anonymous>
```

**Comment by MrCheater** [comment]
Fixed in version 0.18.13
