### ISSUE TITLE
Conflict "react-redux": "^6.0.0" and "react-router-redux": "^5.0.0-alpha.9",

### ISSUE THREAD

**Issue by MrCheater** [reimagined/resolve#967]
**Describe the bug**
Error:
```
browser.js:45 Uncaught Invariant Violation: Could not find "store" in the context of "Connect(TodoList)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(TodoList) in connect options.
    at invariant (http://localhost:3000/static/bundle.js:23456:15)
    at Connect.renderWrappedComponent (http://localhost:3000/static/bundle.js:63135:57)
    at updateContextConsumer (http://localhost:3000/static/bundle.js:55246:19)
    at beginWork (http://localhost:3000/static/bundle.js:55412:14)
    at performUnitOfWork (http://localhost:3000/static/bundle.js:58199:12)
    at workLoop (http://localhost:3000/static/bundle.js:58239:24)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/bundle.js:40198:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/bundle.js:40248:16)
    at invokeGuardedCallback (http://localhost:3000/static/bundle.js:40305:31)
    at replayUnitOfWork (http://localhost:3000/static/bundle.js:57486:5)
react-dom.development.js:16013 The above error occurred in the <Context.Consumer> component:
    in Connect(TodoList) (created by ViewModelContainer)
    in ViewModelContainer (created by Connect(ViewModelContainer))
    in Connect(ViewModelContainer) (created by Context.Consumer)
    in ConnectResolveAdvanced (created by App)
    in div (created by App)
    in App (created by Route)
    in Route (created by Routes)
    in Routes (created by Route)
    in Switch (created by Route)
    in Route (created by Routes)
    in Routes (created by AppContainer)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by AppContainer)
    in Provider (created by Providers)
    in Providers (created by AppContainer)
    in AppContainer

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:16013
utils.js:225 uncaught at loadViewModelStateSaga Invariant Violation: Could not find "store" in the context of "Connect(TodoList)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(TodoList) in connect options.
    at invariant (http://localhost:3000/static/bundle.js:23456:15)
    at Connect.renderWrappedComponent (http://localhost:3000/static/bundle.js:63135:57)
    at updateContextConsumer (http://localhost:3000/static/bundle.js:55246:19)
    at beginWork (http://localhost:3000/static/bundle.js:55412:14)
    at performUnitOfWork (http://localhost:3000/static/bundle.js:58199:12)
    at workLoop (http://localhost:3000/static/bundle.js:58239:24)
    at renderRoot (http://localhost:3000/static/bundle.js:58325:7)
    at performWorkOnRoot (http://localhost:3000/static/bundle.js:59214:7)
    at performWork (http://localhost:3000/static/bundle.js:59126:7)
    at performSyncWork (http://localhost:3000/static/bundle.js:59100:3)
log @ utils.js:225
```

**Comment by MrCheater** [comment]
Fixed in version 0.23.0
